# COPY to docker-compose.yml and run `podman-compose up -d` to start the services

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: basta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n_user -d n8n_database"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    command: redis-server --requirepass myredispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  storage:
    image: minio/minio:latest
    container_name: minio_storage
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge